name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number (semantic)'
        required: true

jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yaml

  release:
    name: Release
    needs: checks
    runs-on: ubuntu-24.04
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'gradle'

      - name: Create tag
        run: |
          git config user.name 'Github Actions'
          git config user.email 'github-actions@users.noreply.github.com'
          git fetch --tags
          git tag "v${{ github.event.inputs.version }}"

      - name: Publish libraries
        run: |
          ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache \
            -PmavenCentralUsername='${{ secrets.MAVEN_CENTRAL_PUBLISHER_USERNAME }}' \
            -PmavenCentralPassword='${{ secrets.MAVEN_CENTRAL_PUBLISHER_PASSWORD }}' \
            -signAllPublications=true \
            -PsigningKey='${{ secrets.GPG_PRIVATE_KEY }}' \
            -PsigningPassword='${{ secrets.GPG_PASSPHRASE }}' \
            -PreleaseVersion='${{ github.event.inputs.version }}'

      - name: Publish plugin
        run: |
          ./gradlew publishPlugins \
            -Pgradle.publish.key='${{ secrets.GRADLE_PUBLISH_KEY }}' \
            -Pgradle.publish.secret='${{ secrets.GRADLE_PUBLISH_SECRET }}' \
            -PsigningKey='${{ secrets.GPG_PRIVATE_KEY }}' \
            -PsigningPassword='${{ secrets.GPG_PASSPHRASE }}' \
            -PreleaseVersion='${{ github.event.inputs.version }}'

      - name: Push tag
        run: |
          git push origin --tags
